"""users orgs and tenancy

Revision ID: 0eca33c7ff8f
Revises: e50608eafb98
Create Date: 2026-09-02

Written by hand rather than autogenerated, because workflows.org_id is NOT NULL
and the table already has rows. Autogenerate would emit a bare add_column that
Postgres rejects outright. Existing workflows are adopted by a "Legacy" org so
the constraint can be added without deleting anything.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0eca33c7ff8f'
down_revision: Union[str, Sequence[str], None] = 'e50608eafb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

LEGACY_SLUG = "legacy"


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'orgs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug', name='uq_orgs_slug'),
    )

    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('org_id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False, server_default='member'),
        sa.Column('is_active', sa.Boolean(), nullable=False,
                  server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['orgs.id'],
                                name='fk_users_org_id'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email', name='uq_users_email'),
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)

    # Nullable first, so existing rows survive the add.
    op.add_column('workflows', sa.Column('org_id', sa.UUID(), nullable=True))
    op.add_column('workflows', sa.Column('created_by', sa.UUID(), nullable=True))

    # Adopt any pre-auth workflows. Created only if there is something to adopt,
    # so a fresh database does not get a stray org.
    op.execute(f"""
        INSERT INTO orgs (id, name, slug, created_at)
        SELECT gen_random_uuid(), 'Legacy', '{LEGACY_SLUG}', now()
        WHERE EXISTS (SELECT 1 FROM workflows)
          AND NOT EXISTS (SELECT 1 FROM orgs WHERE slug = '{LEGACY_SLUG}')
    """)
    op.execute(f"""
        UPDATE workflows
           SET org_id = (SELECT id FROM orgs WHERE slug = '{LEGACY_SLUG}')
         WHERE org_id IS NULL
    """)

    op.alter_column('workflows', 'org_id', nullable=False)
    op.create_index(op.f('ix_workflows_org_id'), 'workflows', ['org_id'],
                    unique=False)
    op.create_foreign_key('fk_workflows_org_id', 'workflows', 'orgs',
                          ['org_id'], ['id'])
    op.create_foreign_key('fk_workflows_created_by', 'workflows', 'users',
                          ['created_by'], ['id'])

    # workflow_runs.created_by existed already, as a bare UUID with no FK.
    op.create_foreign_key('fk_workflow_runs_created_by', 'workflow_runs',
                          'users', ['created_by'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_workflow_runs_created_by', 'workflow_runs',
                       type_='foreignkey')
    op.drop_constraint('fk_workflows_created_by', 'workflows', type_='foreignkey')
    op.drop_constraint('fk_workflows_org_id', 'workflows', type_='foreignkey')
    op.drop_index(op.f('ix_workflows_org_id'), table_name='workflows')
    op.drop_column('workflows', 'created_by')
    op.drop_column('workflows', 'org_id')

    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('orgs')