"""workflow runs and artifacts

Revision ID: e50608eafb98
Revises: c3f213f323cd
Create Date: 2026-08-27 00:17:49.039103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e50608eafb98'
down_revision: Union[str, Sequence[str], None] = 'c3f213f323cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('params_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('node_run_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['node_run_id'], ['node_runs.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_run_id', 'name', name='uq_artifact_noderun_name')
    )
    op.create_index(op.f('ix_artifacts_node_run_id'), 'artifacts', ['node_run_id'], unique=False)
    op.create_index(op.f('ix_artifacts_workflow_run_id'), 'artifacts', ['workflow_run_id'], unique=False)
    op.add_column('node_runs', sa.Column('workflow_run_id', sa.UUID(), nullable=False))
    op.add_column('node_runs', sa.Column('attempt', sa.Integer(), nullable=True))
    op.add_column('node_runs', sa.Column('logs', sa.Text(), nullable=True))
    op.create_index(op.f('ix_node_runs_workflow_run_id'), 'node_runs', ['workflow_run_id'], unique=False)
    op.create_unique_constraint('uq_noderun_run_node', 'node_runs', ['workflow_run_id', 'node_id'])
    op.drop_constraint(op.f('node_runs_workflow_id_fkey'), 'node_runs', type_='foreignkey')
    # Named explicitly: autogenerate passes None here, which makes Postgres
    # auto-name the constraint and then leaves downgrade() unable to drop it.
    op.create_foreign_key('fk_node_runs_workflow_run_id', 'node_runs',
                          'workflow_runs', ['workflow_run_id'], ['id'])
    op.drop_column('node_runs', 'workflow_id')
    op.add_column('workflows', sa.Column('field_boundary_id', sa.UUID(), nullable=True))
    op.add_column('workflows', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_workflows_field_boundary_id', 'workflows',
                          'field_boundaries', ['field_boundary_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workflows_field_boundary_id', 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'updated_at')
    op.drop_column('workflows', 'field_boundary_id')
    op.add_column('node_runs', sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_node_runs_workflow_run_id', 'node_runs', type_='foreignkey')
    op.create_foreign_key(op.f('node_runs_workflow_id_fkey'), 'node_runs', 'workflows', ['workflow_id'], ['id'])
    op.drop_constraint('uq_noderun_run_node', 'node_runs', type_='unique')
    op.drop_index(op.f('ix_node_runs_workflow_run_id'), table_name='node_runs')
    op.drop_column('node_runs', 'logs')
    op.drop_column('node_runs', 'attempt')
    op.drop_column('node_runs', 'workflow_run_id')
    op.drop_index(op.f('ix_artifacts_workflow_run_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_node_run_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    # ### end Alembic commands ###