"""Sentinel-2 nodes.

These stay lazy: each emits a serialised EE object rather than a file, so a
four-node chain costs one download instead of four. export_cog is the explicit
escape hatch when you want an intermediate on disk.
"""

import ee

from app.services.gee.client import aoi_to_ee, ee_init, load_ee_input, serialize
from app.services.gee.collections import (BANDS, NATIVE_SCALE, S2_CLOUD_PROB,
                                          S2_SR, SCL_SHADOW)
from app.services.gee.download import materialize
from app.services.nodes import register_node
from app.services.nodes.base import NodeContext, NoImageryError, Produced

REDUCERS = ("median", "mean", "max", "min", "p90")


def _reducer(name: str):
    """Resolved lazily: ee.Reducer methods are generated by ee.Initialize(),
    so a module-level lookup would fail at import time."""
    ee_init()
    if name == "p90":
        return ee.Reducer.percentile([90])
    return {"median": ee.Reducer.median, "mean": ee.Reducer.mean,
            "max": ee.Reducer.max, "min": ee.Reducer.min}[name]()


@register_node(
    "fetch_sentinel2",
    "Fetch Sentinel-2 L2A surface reflectance imagery for the AOI and date range.",
    inputs={},
    outputs={"raw_s2": "ee_object"},
    params={"max_cloud_pct": "int", "bands": "list[str]"},
    defaults={"max_cloud_pct": 60, "bands": ["B2", "B3", "B4", "B8", "B11"]},
)
def fetch_sentinel2(ctx: NodeContext, inputs):
    ee_init()
    region = aoi_to_ee(ctx.aoi)
    start, end = ctx.date_range["start"], ctx.date_range["end"]

    col = (ee.ImageCollection(S2_SR)
           .filterBounds(region)
           .filterDate(start, end)
           .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", ctx.params["max_cloud_pct"])))

    n = col.size().getInfo()
    if n == 0:
        # This happens routinely; a bare exception string is a poor UX.
        raise NoImageryError(
            f"No Sentinel-2 scenes for this AOI between {start} and {end} under "
            f"{ctx.params['max_cloud_pct']}% cloud. Widen the date range or "
            f"raise max_cloud_pct."
        )

    ts = col.aggregate_array("system:time_start").getInfo()
    return [Produced(
        name="raw_s2", kind="ee_object", value=serialize(col),
        meta={"image_count": n, "collection": S2_SR,
              "first_ts": min(ts), "last_ts": max(ts),
              "max_cloud_pct": ctx.params["max_cloud_pct"]},
    )]


@register_node(
    "cloud_mask",
    "Mask clouds and cloud shadow from a Sentinel-2 collection using the "
    "s2cloudless probability layer.",
    inputs={"raw_s2": "ee_object"},
    outputs={"clean_s2": "ee_object"},
    params={"cloud_prob_thresh": "int"},
    defaults={"cloud_prob_thresh": 40},
)
def cloud_mask(ctx: NodeContext, inputs):
    ee_init()
    col = ee.ImageCollection(load_ee_input(ctx.store, inputs["raw_s2"]))
    thresh = ctx.params["cloud_prob_thresh"]

    # s2cloudless joined on system:index; SCL-only masking is noticeably worse.
    joined = ee.ImageCollection(ee.Join.saveFirst("cloud_prob").apply(
        primary=col,
        secondary=ee.ImageCollection(S2_CLOUD_PROB),
        condition=ee.Filter.equals(leftField="system:index",
                                   rightField="system:index"),
    ))

    def _mask(img):
        img = ee.Image(img)
        prob = ee.Image(img.get("cloud_prob")).select("probability")
        shadow = img.select("SCL").eq(SCL_SHADOW)
        keep = prob.lt(thresh).And(shadow.Not())
        return img.updateMask(keep).copyProperties(img, img.propertyNames())

    return [Produced(
        name="clean_s2", kind="ee_object", value=serialize(joined.map(_mask)),
        meta={"cloud_prob_thresh": thresh, "method": "s2cloudless + SCL shadow"},
    )]


def _index(ctx, inputs, out_name: str, b1: str, b2: str):
    ee_init()
    col = ee.ImageCollection(load_ee_input(ctx.store, inputs["clean_s2"]))
    reducer_name = ctx.params["reducer"]

    idx = col.map(lambda i: ee.Image(i).normalizedDifference([b1, b2]).rename(out_name))
    img = idx.reduce(_reducer(reducer_name)).rename(out_name)

    return [Produced(
        name=out_name, kind="ee_object", value=serialize(img),
        meta={"reducer": reducer_name, "bands": [b1, b2],
              "native_scale_m": max(NATIVE_SCALE[b1], NATIVE_SCALE[b2])},
    )]


@register_node(
    "compute_ndvi",
    "Compute NDVI = (NIR - Red)/(NIR + Red) and reduce the collection over time.",
    inputs={"clean_s2": "ee_object"},
    outputs={"ndvi": "ee_object"},
    params={"reducer": "enum[median|mean|max|min|p90]"},
    defaults={"reducer": "median"},
)
def compute_ndvi(ctx: NodeContext, inputs):
    return _index(ctx, inputs, "ndvi", BANDS["nir"], BANDS["red"])


@register_node(
    "compute_ndmi",
    "Compute NDMI = (NIR - SWIR1)/(NIR + SWIR1), a canopy moisture index, and "
    "reduce the collection over time.",
    inputs={"clean_s2": "ee_object"},
    outputs={"ndmi": "ee_object"},
    params={"reducer": "enum[median|mean|max|min|p90]"},
    defaults={"reducer": "median"},
)
def compute_ndmi(ctx: NodeContext, inputs):
    # B11 is natively 20 m; the common grid resamples it to the target scale.
    return _index(ctx, inputs, "ndmi", BANDS["nir"], BANDS["swir1"])


@register_node(
    "export_cog",
    "Materialize an Earth Engine image to a local GeoTIFF for download or "
    "inspection.",
    inputs={"image": "ee_object"},
    outputs={"cog": "raster"},
    params={"scale": "int", "crs": "str"},
    defaults={"scale": 10, "crs": "EPSG:4326"},
)
def export_cog(ctx: NodeContext, inputs):
    ee_init()
    ref = inputs["image"]
    img = ee.Image(load_ee_input(ctx.store, ref))
    out = ctx.workdir / "export.tif"

    materialize({ref.name: img}, ctx.aoi, out,
                scale=ctx.params["scale"], crs=ctx.params["crs"])

    return [Produced(
        name="cog", kind="raster", local_path=out,
        meta={"scale_m": ctx.params["scale"], "crs": ctx.params["crs"],
              "source": ref.name, "bands": [ref.name]},
    )]